#!/bin/bash
#
## generate python files based on the designer ui files. pyuic5 and pyrcc5
# should be on the path.

set -e

if [ ! -d "designer" ]
then
	echo "Please run this from the project root"
	exit
fi

mkdir -p tictac/forms

init=tictac/forms/__init__.py
# to store the names of the generated python files
temp=tictac/forms/scratch

rm -f $init $temp
echo "# This file auto-generated by build_ui.sh. Don't edit." > $init
echo "__all__ = [" >> $init

echo "Generating forms.."
for i in designer/*.ui
do
	base=$(basename $i .ui)
	py="tictac/forms/${base}.py"
	echo "	\"$base\"," >> $init
	echo "from . import $base" >> $temp
	pyuic5 -o $py $i
done

echo "]" >> $init
cat $temp >> $init
rm $temp
