# Generated by Django 2.2.3 on 2019-07-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('board_x', models.BinaryField(default=0, editable=True)),
                ('board_o', models.BinaryField(default=0, editable=True)),
                ('player_x', models.CharField(max_length=64)),
                ('player_o', models.CharField(max_length=64)),
                ('n_rows', models.IntegerField(default=3)),
                ('n_cols', models.IntegerField(default=3)),
                ('n_connects', models.IntegerField(default=3)),
                ('is_kriegspiel', models.BooleanField(default=False)),
            ],
        ),
    ]
