# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/newgame.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewGameDialog(object):
    def setupUi(self, NewGameDialog):
        NewGameDialog.setObjectName("NewGameDialog")
        NewGameDialog.resize(380, 280)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../main/icons/base/window-icon/128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewGameDialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewGameDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(NewGameDialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 361, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.GameTab = QtWidgets.QWidget()
        self.GameTab.setObjectName("GameTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.GameTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.GameTab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.GameTab)
        self.spinBox.setMinimum(3)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.GameTab)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.spinBox_2 = QtWidgets.QSpinBox(self.GameTab)
        self.spinBox_2.setMinimum(3)
        self.spinBox_2.setMaximum(5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_5.addWidget(self.spinBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.GameTab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.GameTab)
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(99)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_6.addWidget(self.spinBox_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.GameTab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.spinBox_3 = QtWidgets.QSpinBox(self.GameTab)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(99)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_7.addWidget(self.spinBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.GameTab, "")
        self.Player1Tab = QtWidgets.QWidget()
        self.Player1Tab.setObjectName("Player1Tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Player1Tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.Player1Tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.Player1Tab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.checkBox_3 = QtWidgets.QCheckBox(self.Player1Tab)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_5.addWidget(self.checkBox_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.Player1Tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.comboBox_4 = QtWidgets.QComboBox(self.Player1Tab)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.tabWidget.addTab(self.Player1Tab, "")
        self.Player2Tab = QtWidgets.QWidget()
        self.Player2Tab.setObjectName("Player2Tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Player2Tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.Player2Tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Player2Tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_11.addWidget(self.lineEdit_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.checkBox_4 = QtWidgets.QCheckBox(self.Player2Tab)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_6.addWidget(self.checkBox_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.Player2Tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.Player2Tab)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.tabWidget.addTab(self.Player2Tab, "")

        self.retranslateUi(NewGameDialog)
        self.tabWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(NewGameDialog.accept)
        self.buttonBox.rejected.connect(NewGameDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewGameDialog)

    def retranslateUi(self, NewGameDialog):
        _translate = QtCore.QCoreApplication.translate
        NewGameDialog.setWindowTitle(_translate("NewGameDialog", "New game"))
        self.label_2.setText(_translate("NewGameDialog", "No. of columns"))
        self.label.setText(_translate("NewGameDialog", "No. of rows"))
        self.label_3.setText(_translate("NewGameDialog", "No. of games"))
        self.label_4.setText(_translate("NewGameDialog", "Wins first to"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GameTab), _translate("NewGameDialog", "Game"))
        self.label_7.setText(_translate("NewGameDialog", "Name"))
        self.checkBox_3.setText(_translate("NewGameDialog", "is human?"))
        self.label_6.setText(_translate("NewGameDialog", "Strategy"))
        self.comboBox_4.setItemText(0, _translate("NewGameDialog", "Minimax"))
        self.comboBox_4.setItemText(1, _translate("NewGameDialog", "Minimax with alpha beta pruning"))
        self.comboBox_4.setItemText(2, _translate("NewGameDialog", "Minimax with caching"))
        self.comboBox_4.setItemText(3, _translate("NewGameDialog", "Minimax with alpha beta pruning and caching"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Player1Tab), _translate("NewGameDialog", "Player 1"))
        self.label_8.setText(_translate("NewGameDialog", "Name"))
        self.checkBox_4.setText(_translate("NewGameDialog", "is human?"))
        self.label_5.setText(_translate("NewGameDialog", "Strategy"))
        self.comboBox_2.setItemText(0, _translate("NewGameDialog", "Minimax"))
        self.comboBox_2.setItemText(1, _translate("NewGameDialog", "Minimax with alpha beta pruning"))
        self.comboBox_2.setItemText(2, _translate("NewGameDialog", "Minimax with caching"))
        self.comboBox_2.setItemText(3, _translate("NewGameDialog", "Minimax with alpha beta pruning and caching"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Player2Tab), _translate("NewGameDialog", "Player 2"))

