# Generated by Django 2.2.4 on 2019-08-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_x', models.PositiveIntegerField(default=0)),
                ('board_o', models.PositiveIntegerField(default=0)),
                ('n_rows', models.IntegerField(default=3)),
                ('n_cols', models.IntegerField(default=3)),
                ('n_connects', models.IntegerField(default=3)),
                ('depth', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('board_x', models.IntegerField(default=0)),
                ('board_o', models.IntegerField(default=0)),
                ('player_x', models.CharField(max_length=64)),
                ('player_o', models.CharField(max_length=64)),
                ('n_rows', models.IntegerField(default=3)),
                ('n_cols', models.IntegerField(default=3)),
                ('n_connects', models.IntegerField(default=3)),
                ('is_kriegspiel', models.BooleanField(default=False)),
            ],
        ),
    ]
