# Generated by Django 2.2.4 on 2019-08-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board_o',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='board_x',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
