# Generated by Django 2.2.3 on 2019-07-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo', '0002_auto_20190727_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_x', models.PositiveIntegerField(default=0)),
                ('board_o', models.PositiveIntegerField(default=0)),
                ('n_rows', models.IntegerField(default=3)),
                ('n_cols', models.IntegerField(default=3)),
                ('n_connects', models.IntegerField(default=3)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='n_cols',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='n_connects',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='n_rows',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
