# Generated by Django 2.2.3 on 2019-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo', '0003_auto_20190728_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardstate',
            name='is_max',
            field=models.BooleanField(default=True),
        ),
    ]
