# Generated by Django 2.2.3 on 2019-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo', '0004_boardstate_is_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardstate',
            name='is_max',
        ),
        migrations.AddField(
            model_name='boardstate',
            name='is_exact',
            field=models.BooleanField(default=False),
        ),
    ]
