# Generated by Django 2.2.3 on 2019-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo', '0006_remove_boardstate_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardstate',
            name='is_exact',
        ),
        migrations.AddField(
            model_name='boardstate',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
