# Generated by Django 2.2.3 on 2019-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo', '0007_auto_20190728_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardstate',
            name='depth',
            field=models.IntegerField(default=0),
        ),
    ]
